language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: cicd-practice
  api_key:
    secure: G5l6o25PxEWUsQn7JJMdlE4f7EJ5UUIf36gcuyl2H9Ovyvd9PXjAiz/naRIRvSPcDDI//o/GmhTYGB+sjc3h6jTNYLIYQO6dTjZPbXGB/bt3d8pVzU55AIqwxK072IrxZxmGnMH3mlftyN+fcAILHHMyPwNBZg03NVmVWsftCXBbzLT0Px8/1b2nbHAdQqa5hYxv+6gNnfZqE1cTNRa02dy2dXBmUqPNmbDt145wjfV3KjA1aF6WNTnZIha3h12jDguctKeUNXdoirPAHe4FTKqQSFhwjZtOknKFBVMRVju4ZWPkE857ueFofB42Zaw/YXR++XJ7JjSvTJvfCtqBxke5KqYC17+pAO6KgZs6JHF5d7v+R/FkPYIqFgGNn5vrWI1Xx5242HSBvtNwhazRMrFmpEJlHCV5+5EXNTPINlb3Oo5uS5pHKDuz4B8lyB5Ke0vDI8gV6WBmkH3YOzYWnjZpcw4Bcl7qa+nrhaKv3OcjY3XkjH0/HRC3RCH1GygoBxPjTmHNAXgUU+nO9/EtdPASnj68/n80jTEe1K91VqtjUevHLtfpqENeSmdIBY305ucB8X3Xj+s2iBV6b07n+PGxeigoaZzAAdHcJZo8ejfesB6GQAAjoNhgaQ2XgE+yo86hm2nodzoFOknaW19cijdL6ZDtJkUrCpfigpdytpg=
